### ISSUE TITLE
seek for results

### ISSUE THREAD

**Issue by tourist-wwj** [AlbertTan404/NA-GSL#1]
Hi, It's nice to read your insightful work. When repeating your code, the MSE is a bit higher than your results in the thesis. For AIDS, the result is about 2.2(1.622 in your thesis). I wonder whether it's the problem caused by parameters. Could you please show me the best parameters in your model? Thank you very much!
What's more, I wonder your repeating results of SimGNN , which is 1.367 in the thesis. However, I can only repeat the results of around 2.5 and it's similar with the other coder's results. Thank you very much!

**Comment by AlbertTan404** [comment]
Thanks for your comments! 
For the first question, I apologize for missing the correct hyper-parameter to reproduce the results. Cuz it's really long time ago and I can't recall that (I graduated and lost access to the server which I run the experiments with). To the best of my knowledge, hidden size for AIDS should be larger due to its heterogeneousness and multi-lable. You may try a larger hidden size and attn heads.
I FAILED to reproduce the results of SimGNN (it seems that few people did that according to the original repo's issues). I used the reproduction of H2MN to fair comparison, so some of the code in this repo comes from H2MN's.

**Comment by tourist-wwj** [comment]
Thanks for your quick reply and great guidance!
